### ISSUE TITLE
I unable to run

### ISSUE THREAD

**Issue by bandarikanth** [brynbellomy/solidity-auction#2]
I unable to run the example.it,s showing many errors. I aatached that. Can you slove it
![screenshot from 2018-05-11 14-18-12]

(https://user-images.githubusercontent.com/26737645/39915693-390918a4-5526-11e8-9bd3-6c0215840f09.png)

**Comment by brynbellomy** [comment]
It looks like the issue is related to an npm module called `truffle-webpack`.  I'm not familiar with this module, and it's not a part of this repo, so I'm afraid I can't help.
